/**
 * Centralised environment access.
 *
 * Every variable is read through an explicit `process.env.X` expression so the
 * values can be statically inlined by Next.js (required for the Edge runtime).
 *
 * SERVER ONLY. None of these are `NEXT_PUBLIC_`, so they are erased from the
 * browser bundle. Importing this module from a `"use client"` module — even
 * indirectly, via a shared module that a client component imports — would make
 * `required()` blow up in the browser. Pass values down as props instead.
 *
 * `import "server-only"` is intentionally *not* used: it throws under plain
 * Node, and several `scripts/*.ts` run through `tsx` and reach this module.
 * The guard below achieves the same protection across every runtime.
 */
if (typeof window !== "undefined") {
  throw new Error(
    "src/lib/env.ts was bundled into the browser. It reads server-only " +
      "environment variables and must not be imported from a Client Component. " +
      "Read it in a Server Component and pass the value down as a prop.",
  );
}

function required(name: string, value: string | undefined): string {
  if (!value || value.trim() === "") {
    throw new Error(
      `Missing required environment variable "${name}". ` +
        `Copy .env.example to .env and fill it in.`,
    );
  }
  return value.trim();
}

function optionalNumber(value: string | undefined, fallback: number): number {
  const parsed = Number.parseInt(value ?? "", 10);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function optionalFloat(value: string | undefined, fallback: number): number {
  const parsed = Number.parseFloat(value ?? "");
  return Number.isFinite(parsed) ? parsed : fallback;
}

const smtpUser = process.env.SMTP_USER?.trim() ?? "";
const smtpPassword = process.env.SMTP_PASSWORD?.trim() ?? "";
const smtpHost = process.env.SMTP_HOST?.trim() ?? "";
const appName = process.env.APP_NAME?.trim() || "MSCrossWords";

export const env = {
  APP_NAME: appName,

  DATABASE_URL: required("DATABASE_URL", process.env.DATABASE_URL),

  /* ------------------------------- SMTP -------------------------------- */
  SMTP_HOST: smtpHost,
  SMTP_PORT: optionalNumber(process.env.SMTP_PORT, 587),
  SMTP_USER: smtpUser,
  SMTP_PASSWORD: smtpPassword,
  SMTP_FROM:
    process.env.SMTP_FROM?.trim() ||
    (smtpUser ? `${appName} <${smtpUser}>` : ""),

  OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY?.trim() ?? "",
  OPENROUTER_MODEL:
    process.env.OPENROUTER_MODEL?.trim() || "openai/gpt-4o-mini",
  OPENROUTER_BASE_URL:
    process.env.OPENROUTER_BASE_URL?.trim() || "https://openrouter.ai/api/v1",

  /** Public URL used by OpenRouter's attribution headers (optional). */
  APP_URL:
    process.env.APP_URL?.trim() ||
    (process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}`
      : "http://localhost:3000"),

  /** How many words a generated crossword should aim for. */
  CROSSWORD_TARGET_WORDS: optionalNumber(
    process.env.CROSSWORD_TARGET_WORDS,
    12,
  ),
  /** Size of the candidate pool drawn from the user's vocabulary. */
  CROSSWORD_CANDIDATE_POOL: optionalNumber(
    process.env.CROSSWORD_CANDIDATE_POOL,
    40,
  ),
  /** Share of clues generated by the AI (the rest use the PT translation). */
  CROSSWORD_AI_CLUE_RATIO: optionalFloat(
    process.env.CROSSWORD_AI_CLUE_RATIO,
    0.5,
  ),
} as const;

export const isAiEnabled = env.OPENROUTER_API_KEY.length > 0;

/** Without SMTP the app still works; only "esqueci minha senha" is disabled. */
export const isEmailEnabled =
  env.SMTP_HOST.length > 0 &&
  env.SMTP_USER.length > 0 &&
  env.SMTP_PASSWORD.length > 0;
